### ISSUE TITLE
(Question) How to insert a tab, instead of triggering the completion?

### ISSUE THREAD

**Issue by rdmartins** [ackyshake/VimCompletesMe#73]
Let's say I'm adding a new line to my fstab.
So, after I written the second column (the mountpoint) I want to make a tab and write the third column (the type).
Today, my solution is to type a space, and then press the tab key... Am I just being too dumb, or this is the way to do it?

Thanks for your time, and thanks more for the plugin.

**Comment by ackyshake** [comment]
Yeah that's currently the way to do it, if you're using Tab as the completion trigger key. The reason for that is that there's no easy way to tell if the user wants completion after a word character or inserting Tab/spaces when they hit the Tab key.

Alternatively, you could unset `vcm_default_maps` in your ~/.vimrc and [choose another key](https://github.com/ackyshake/VimCompletesMe/blob/master/plugin/VimCompletesMe.vim#L29,L32) which would trigger completion. 

Hope this helps!
