### ISSUE TITLE
insert a <TAB> character (\t)

### ISSUE THREAD

**Issue by drbeco** [ackyshake/VimCompletesMe#76]
Is there a simple way to insert a real `TAB` when you need \t and don't want to autocomplete?

Thanks

**Comment by ackyshake** [comment]
Yep, you can use `Ctrl-v` in insert mode, and then press the Tab key.

See `:help `i_CTRL-V` for the documentation on that.

**Comment by drbeco** [comment]
Thanks, but `CTRL-V` is a bit cumbersome.

I did the following map:

```
 :inoremap <Tab><Tab> <C-v><Tab>
```

Now I can just press `<TAB>` twice and I'm good.
