### ISSUE TITLE
Generic completion

### ISSUE THREAD

**Issue by DharminB** [ackyshake/VimCompletesMe#77]
Is is possible to configure VimCompletesMe to use generic completion (`:h compl-generic`)?

**My use case**:
 I have multiple cpp buffers open in the background. For some word completions, VimCompletesMe returns no results when I press `Tab` and says `Looking for members...` , then I press `Tab` again to switch context, and it still returns no results while saying `Falling back to keyword`. But I know that the word that I want to be inserted is in an open buffer in the background.

When I try to manually do the completion key press of `i_Ctrl-X_Ctrl-O` or `i_Ctrl-X_Ctrl-N` no completions are done either. So, it makes sense that VimCompletesMe suggests no completions. But when I do `i_Ctrl-N`, then the completion works exactly as I would like.

**My config**:
- vim 8.0
- `completeopt=menu,menuone,longest`
- `complete=.,w,b,u,t,i`

Please let me know if additional information/configurations are required.

**Comment by ackyshake** [comment]
Yeah, currently VCM falls back to local keyword completion (`compl-current`) when using omnifunc, but I agree with you that there should be an option to tweak the behavior of that fallback to use `compl-generic`.

My thinking when using `compl-current` for the fallback was that was that Ctrl-N and Ctrl-P were slower in my experience (especially depending on the configuration of `&complete`). Additionally, it's easier to type Ctrl-N/Ctrl-P when you know the word you're trying to complete isn't contained in the current file.

I think Vim doesn't truly provide a good way to verify whether or not there would be valid completions for a completion type. However, there may be certain techniques I could use to prefer `compl-generic` over `compl-current`. For example, if the current file doesn't contain the word that is being completed, VCM could use the more generic keyword completion over the current buffer completion.

I'm going to experiment with that, and see if I can improve the current behavior.

**Comment by DharminB** [comment]
For now, I have changed 
https://github.com/ackyshake/VimCompletesMe/blob/2c69e30675d2a30208099742d14bd661d99fc5f2/autoload/VimCompletesMe.vim#L35

to 

```
      let exp = "\<C-e>" . dirs[!dir]
```

But I am eagerly waiting for your experiment results/improvements.

**Comment by ackyshake** [comment]
@DharminB This should be fixed in 9adf692, and fallback completion should now be little more smarter.

Thanks for reporting the issue! Let me know if you have any issues with it.
